services:
    laravel.test:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
            - oracle

    pgsql:
        image: 'postgres:${POSTGRES_VERSION:-15}'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
            retries: 3
            timeout: 5s

    oracle:
        image: gvenzl/oracle-xe
        container_name: oracle_db
        ports:
            - "1521:1521"
            - "5500:5500"  
        environment:
            ORACLE_PASSWORD: '${ORACLE_PASSWORD:-oracle}'
            ORACLE_USER: '${ORACLE_USER:-system}'
            ORACLE_PDB: '${ORACLE_PDB:-XE}'
        networks:
            - sail
        volumes:
            - oracle-data:/opt/oracle/oradata
        restart: always

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/${ORACLE_PASSWORD}@localhost:1521/XEPDB1"]
            interval: 30s
            timeout: 10s
            retries: 10

networks:
    sail:
        driver: bridge

volumes:
    oracle-data:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
